import { SeedProduct } from './types';

export const dressProducts: SeedProduct[] = [
  // === DR-01 → DR-06 (đã có ở trên) ===

  {
    sku: "DR-07",
    title: "Đầm maxi hoa cổ V xẻ tà",
    brand: "Forever 21",
    productTypeName: "Casual Dress",
    conditionValue: "excellent",
    sizeLabel: "M",
    color: "Hoa đỏ",
    material: "Chiffon",
    style: "Bohemian",
    ecoImpactGroup: "Dress",
    oldPrice: 1450000,
    newPrice: 590000,
    inventory: 1,
    images: [
      { id: "dr07-front", alt: "Đầm maxi hoa cổ V - mặt trước", main: "/assets/images/main/dress-07-front.jpg", thumb: "/assets/images/thumb/dress-07-front-thumb.jpg" },
      { id: "dr07-back", alt: "Đầm maxi hoa cổ V - mặt sau", main: "/assets/images/main/dress-07-back.jpg", thumb: "/assets/images/thumb/dress-07-back-thumb.jpg" },
    ],
    description: "Maxi chiffon hoa, cổ V, xẻ tà duyên dáng.",
    estimatedRetailInfo: { estimatedOriginalPrice: 1450000, source: "Retail Estimate" },
  },
  {
    sku: "DR-08",
    title: "Đầm midi hai dây satin",
    brand: "Topshop",
    productTypeName: "Cocktail Dress",
    conditionValue: "very good",
    sizeLabel: "S",
    color: "Xanh navy",
    material: "Satin",
    style: "Elegant",
    ecoImpactGroup: "Dress",
    oldPrice: 1600000,
    newPrice: 620000,
    inventory: 1,
    images: [
      { id: "dr08-front", alt: "Đầm midi hai dây satin - mặt trước", main: "/assets/images/main/dress-08-front.jpg", thumb: "/assets/images/thumb/dress-08-front-thumb.jpg" },
      { id: "dr08-back", alt: "Đầm midi hai dây satin - mặt sau", main: "/assets/images/main/dress-08-back.jpg", thumb: "/assets/images/thumb/dress-08-back-thumb.jpg" },
    ],
    description: "Midi satin sang trọng, phù hợp tiệc tối.",
    estimatedRetailInfo: { estimatedOriginalPrice: 1600000, source: "Retail Estimate" },
  },
  {
    sku: "DR-09",
    title: "Đầm mini thun bodycon",
    brand: "Shein",
    productTypeName: "Casual Dress",
    conditionValue: "good",
    sizeLabel: "XS",
    color: "Đỏ",
    material: "Cotton Spandex",
    style: "Sexy",
    ecoImpactGroup: "Dress",
    oldPrice: 750000,
    newPrice: 250000,
    inventory: 1,
    images: [
      { id: "dr09-front", alt: "Đầm mini bodycon đỏ - mặt trước", main: "/assets/images/main/dress-09-front.jpg", thumb: "/assets/images/thumb/dress-09-front-thumb.jpg" },
      { id: "dr09-back", alt: "Đầm mini bodycon đỏ - mặt sau", main: "/assets/images/main/dress-09-back.jpg", thumb: "/assets/images/thumb/dress-09-back-thumb.jpg" },
    ],
    description: "Đầm bodycon ngắn, co giãn, ôm dáng.",
    estimatedRetailInfo: { estimatedOriginalPrice: 750000, source: "Retail Estimate" },
  },
  {
    sku: "DR-10",
    title: "Đầm trắng ren dáng xòe",
    brand: "Chicwish",
    productTypeName: "Cocktail Dress",
    conditionValue: "excellent",
    sizeLabel: "M",
    color: "Trắng",
    material: "Ren",
    style: "Romantic",
    ecoImpactGroup: "Dress",
    oldPrice: 1900000,
    newPrice: 750000,
    inventory: 1,
    images: [
      { id: "dr10-front", alt: "Đầm trắng ren dáng xòe - mặt trước", main: "/assets/images/main/dress-10-front.jpg", thumb: "/assets/images/thumb/dress-10-front-thumb.jpg" },
      { id: "dr10-back", alt: "Đầm trắng ren dáng xòe - mặt sau", main: "/assets/images/main/dress-10-back.jpg", thumb: "/assets/images/thumb/dress-10-back-thumb.jpg" },
    ],
    description: "Ren tinh tế, dáng xòe nữ tính, đi tiệc cưới.",
    estimatedRetailInfo: { estimatedOriginalPrice: 1900000, source: "Retail Estimate" },
  },
  {
    sku: "DR-11",
    title: "Đầm midi cotton kẻ sọc",
    brand: "Gap",
    productTypeName: "Casual Dress",
    conditionValue: "good",
    sizeLabel: "L",
    color: "Sọc xanh trắng",
    material: "Cotton",
    style: "Everyday",
    ecoImpactGroup: "Dress",
    oldPrice: 990000,
    newPrice: 390000,
    inventory: 1,
    images: [
      { id: "dr11-front", alt: "Đầm midi cotton sọc - mặt trước", main: "/assets/images/main/dress-11-front.jpg", thumb: "/assets/images/thumb/dress-11-front-thumb.jpg" },
      { id: "dr11-back", alt: "Đầm midi cotton sọc - mặt sau", main: "/assets/images/main/dress-11-back.jpg", thumb: "/assets/images/thumb/dress-11-back-thumb.jpg" },
    ],
    description: "Cotton thoải mái, kẻ sọc basic dễ phối.",
    estimatedRetailInfo: { estimatedOriginalPrice: 990000, source: "Retail Estimate" },
  },
  {
    sku: "DR-12",
    title: "Đầm maxi trễ vai boho",
    brand: "Anthropologie",
    productTypeName: "Casual Dress",
    conditionValue: "very good",
    sizeLabel: "M",
    color: "Vàng hoa",
    material: "Cotton",
    style: "Boho / Summer",
    ecoImpactGroup: "Dress",
    oldPrice: 2200000,
    newPrice: 880000,
    inventory: 1,
    images: [
      { id: "dr12-front", alt: "Đầm maxi trễ vai boho - mặt trước", main: "/assets/images/main/dress-12-front.jpg", thumb: "/assets/images/thumb/dress-12-front-thumb.jpg" },
      { id: "dr12-back", alt: "Đầm maxi trễ vai boho - mặt sau", main: "/assets/images/main/dress-12-back.jpg", thumb: "/assets/images/thumb/dress-12-back-thumb.jpg" },
    ],
    description: "Maxi trễ vai phóng khoáng, boho vibe.",
    estimatedRetailInfo: { estimatedOriginalPrice: 2200000, source: "Retail Estimate" },
  },
  {
    sku: "DR-13",
    title: "Đầm midi voan tay dài",
    brand: "Zara",
    productTypeName: "Casual Dress",
    conditionValue: "flawed gem",
    sizeLabel: "S",
    color: "Be chấm bi",
    material: "Voan",
    style: "Vintage Inspired",
    ecoImpactGroup: "Dress",
    oldPrice: 1350000,
    newPrice: 350000,
    inventory: 1,
    images: [
      { id: "dr13-front", alt: "Đầm voan tay dài - mặt trước", main: "/assets/images/main/dress-13-front.jpg", thumb: "/assets/images/thumb/dress-13-front-thumb.jpg" },
      { id: "dr13-back", alt: "Đầm voan tay dài - mặt sau", main: "/assets/images/main/dress-13-back.jpg", thumb: "/assets/images/thumb/dress-13-back-thumb.jpg" },
    ],
    description: "Có vết ố nhẹ phần tay áo, vẫn mặc đẹp.",
    estimatedRetailInfo: { estimatedOriginalPrice: 1350000, source: "Retail Estimate" },
  },
  {
    sku: "DR-14",
    title: "Đầm slip dress satin cổ V",
    brand: "Everlane",
    productTypeName: "Cocktail Dress",
    conditionValue: "excellent",
    sizeLabel: "M",
    color: "Đỏ rượu",
    material: "Satin",
    style: "Minimal",
    ecoImpactGroup: "Dress",
    oldPrice: 2100000,
    newPrice: 920000,
    inventory: 1,
    images: [
      { id: "dr14-front", alt: "Slip dress satin cổ V - mặt trước", main: "/assets/images/main/dress-14-front.jpg", thumb: "/assets/images/thumb/dress-14-front-thumb.jpg" },
      { id: "dr14-back", alt: "Slip dress satin cổ V - mặt sau", main: "/assets/images/main/dress-14-back.jpg", thumb: "/assets/images/thumb/dress-14-back-thumb.jpg" },
    ],
    description: "Slip dress satin mềm mại, cổ V quyến rũ.",
    estimatedRetailInfo: { estimatedOriginalPrice: 2100000, source: "Retail Estimate" },
  },
  {
    sku: "DR-15",
    title: "Đầm midi linen cổ tròn",
    brand: "COS",
    productTypeName: "Casual Dress",
    conditionValue: "very good",
    sizeLabel: "L",
    color: "Xám nhạt",
    material: "Linen",
    style: "Minimal / Workwear",
    ecoImpactGroup: "Dress",
    oldPrice: 2500000,
    newPrice: 1100000,
    inventory: 1,
    images: [
      { id: "dr15-front", alt: "Đầm linen cổ tròn - mặt trước", main: "/assets/images/main/dress-15-front.jpg", thumb: "/assets/images/thumb/dress-15-front-thumb.jpg" },
      { id: "dr15-back", alt: "Đầm linen cổ tròn - mặt sau", main: "/assets/images/main/dress-15-back.jpg", thumb: "/assets/images/thumb/dress-15-back-thumb.jpg" },
    ],
    description: "Chất linen sang trọng, basic, dễ mặc.",
    estimatedRetailInfo: { estimatedOriginalPrice: 2500000, source: "Retail Estimate" },
  },
  {
    sku: "DR-16",
    title: "Đầm dạ hội sequin ôm body",
    brand: "BCBG",
    productTypeName: "Cocktail Dress",
    conditionValue: "excellent",
    sizeLabel: "S",
    color: "Bạc",
    material: "Sequin",
    style: "Glam",
    ecoImpactGroup: "Dress",
    oldPrice: 4500000,
    newPrice: 1850000,
    inventory: 1,
    images: [
      { id: "dr16-front", alt: "Đầm sequin ôm body - mặt trước", main: "/assets/images/main/dress-16-front.jpg", thumb: "/assets/images/thumb/dress-16-front-thumb.jpg" },
      { id: "dr16-back", alt: "Đầm sequin ôm body - mặt sau", main: "/assets/images/main/dress-16-back.jpg", thumb: "/assets/images/thumb/dress-16-back-thumb.jpg" },
    ],
    description: "Sequin lấp lánh, chuẩn dạ hội.",
    estimatedRetailInfo: { estimatedOriginalPrice: 4500000, source: "Retail Estimate" },
  },
  {
    sku: "DR-17",
    title: "Đầm sơ mi denim cộc tay",
    brand: "Levi’s",
    productTypeName: "Casual Dress",
    conditionValue: "good",
    sizeLabel: "M",
    color: "Xanh jean",
    material: "Denim",
    style: "Casual / Everyday",
    ecoImpactGroup: "Dress",
    oldPrice: 1700000,
    newPrice: 650000,
    inventory: 1,
    images: [
      { id: "dr17-front", alt: "Đầm sơ mi denim - mặt trước", main: "/assets/images/main/dress-17-front.jpg", thumb: "/assets/images/thumb/dress-17-front-thumb.jpg" },
      { id: "dr17-back", alt: "Đầm sơ mi denim - mặt sau", main: "/assets/images/main/dress-17-back.jpg", thumb: "/assets/images/thumb/dress-17-back-thumb.jpg" },
    ],
    description: "Denim cá tính, dễ phối giày sneakers.",
    estimatedRetailInfo: { estimatedOriginalPrice: 1700000, source: "Retail Estimate" },
  },
  {
    sku: "DR-18",
    title: "Đầm mini cổ yếm ôm sát",
    brand: "Bershka",
    productTypeName: "Casual Dress",
    conditionValue: "very good",
    sizeLabel: "XS",
    color: "Hồng neon",
    material: "Polyester",
    style: "Trendy / Night out",
    ecoImpactGroup: "Dress",
    oldPrice: 890000,
    newPrice: 360000,
    inventory: 1,
    images: [
      { id: "dr18-front", alt: "Đầm mini cổ yếm ôm - mặt trước", main: "/assets/images/main/dress-18-front.jpg", thumb: "/assets/images/thumb/dress-18-front-thumb.jpg" },
      { id: "dr18-back", alt: "Đầm mini cổ yếm ôm - mặt sau", main: "/assets/images/main/dress-18-back.jpg", thumb: "/assets/images/thumb/dress-18-back-thumb.jpg" },
    ],
    description: "Mini dress cổ yếm trẻ trung, hợp party.",
    estimatedRetailInfo: { estimatedOriginalPrice: 890000, source: "Retail Estimate" },
  },
  {
    sku: "DR-19",
    title: "Đầm maxi cổ yếm lụa trơn",
    brand: "Massimo Dutti",
    productTypeName: "Cocktail Dress",
    conditionValue: "excellent",
    sizeLabel: "M",
    color: "Ngọc lục bảo",
    material: "Lụa",
    style: "Luxury",
    ecoImpactGroup: "Dress",
    oldPrice: 3500000,
    newPrice: 1450000,
    inventory: 1,
    images: [
      { id: "dr19-front", alt: "Đầm maxi cổ yếm lụa - mặt trước", main: "/assets/images/main/dress-19-front.jpg", thumb: "/assets/images/thumb/dress-19-front-thumb.jpg" },
      { id: "dr19-back", alt: "Đầm maxi cổ yếm lụa - mặt sau", main: "/assets/images/main/dress-19-back.jpg", thumb: "/assets/images/thumb/dress-19-back-thumb.jpg" },
    ],
    description: "Maxi lụa sang trọng, chuẩn sự kiện.",
    estimatedRetailInfo: { estimatedOriginalPrice: 3500000, source: "Retail Estimate" },
  },
  {
    sku: "DR-20",
    title: "Đầm vintage hoa cổ Peter Pan",
    brand: "Thrift",
    productTypeName: "Dress",
    conditionValue: "flawed gem",
    sizeLabel: "L",
    color: "Hoa vàng",
    material: "Cotton",
    style: "Vintage",
    ecoImpactGroup: "Dress",
    oldPrice: 950000,
    newPrice: 280000,
    inventory: 1,
    images: [
      { id: "dr20-front", alt: "Đầm vintage hoa cổ Peter Pan - mặt trước", main: "/assets/images/main/dress-20-front.jpg", thumb: "/assets/images/thumb/dress-20-front-thumb.jpg" },
      { id: "dr20-back", alt: "Đầm vintage hoa cổ Peter Pan - mặt sau", main: "/assets/images/main/dress-20-back.jpg", thumb: "/assets/images/thumb/dress-20-back-thumb.jpg" },
    ],
    description: "Có vết sờn cổ áo, form vintage độc đáo.",
    estimatedRetailInfo: { estimatedOriginalPrice: 950000, source: "Retail Estimate" },
  },
];
